---
# http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

# Adding the PPA
- apt_repository: repo='ppa:webupd8team/java' update_cache=yes

# Auto-accepting license:
- shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

# Installing
- apt: name='oracle-java8-installer'
